// Date: 2016/04/06 19:25:59
// Template version 1.1
// Java generated by Techne
// Keep in mind that you still need to fill in some blanks
// - ZeuX






package com.kanomiya.mcmod.touchablecontainercraft.client.render;

import net.minecraft.client.model.ModelBase;
import net.minecraft.client.model.ModelRenderer;
import net.minecraft.entity.Entity;

public class ModelIngot extends ModelBase
{
	//fields
	ModelRenderer m11;

	public ModelIngot()
	{
		textureWidth = 32;
		textureHeight = 32;

		m11 = new ModelRenderer(this, 0, 0);
		m11.addBox(0F, 0F, 0F, 12, 3, 3);
		m11.setRotationPoint(0F, 0F, 0F);
		m11.setTextureSize(32, 32);
	}

	@Override
	public void render(Entity entityIn, float p_78088_2_, float p_78088_3_, float p_78088_4_, float p_78088_5_, float p_78088_6_, float scale)
	{
		setRotationAngles(p_78088_2_, p_78088_3_, p_78088_4_, p_78088_5_, p_78088_6_, scale, entityIn);
		doRender(scale);
	}

	public void doRender(float f)
	{
		m11.render(f);
	}

}
